// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8sSU6gnaOS2cmFo8FFZvGZAfczag-EKo',
    appId: '1:607431229012:android:fc9f854b920a0883bef7c1',
    messagingSenderId: '607431229012',
    projectId: 'flutter-firebase-codelab-2',
    storageBucket: 'flutter-firebase-codelab-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBQ6jc_F2CUH9-hwEwblP1jQs7-tL_68U',
    appId: '1:607431229012:ios:554ba707abb91a99bef7c1',
    messagingSenderId: '607431229012',
    projectId: 'flutter-firebase-codelab-2',
    storageBucket: 'flutter-firebase-codelab-2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2HLc6eXJAttCWrG8QrzlFtxHDWETaSZ0',
    appId: '1:607431229012:web:3270cb90400d85e8bef7c1',
    messagingSenderId: '607431229012',
    projectId: 'flutter-firebase-codelab-2',
    authDomain: 'flutter-firebase-codelab-2.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-2.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HLc6eXJAttCWrG8QrzlFtxHDWETaSZ0',
    appId: '1:607431229012:web:3270cb90400d85e8bef7c1',
    messagingSenderId: '607431229012',
    projectId: 'flutter-firebase-codelab-2',
    authDomain: 'flutter-firebase-codelab-2.firebaseapp.com',
    storageBucket: 'flutter-firebase-codelab-2.firebasestorage.app',
  );

}